name: QiitaVIPER
options:
  bundleIdPrefix: kimiaki.QiitaVIPER
  deploymentTarget: "13.0"
  groupSortPosition: top
  minimumXcodeGenVersion: 2.15.0
  carthageExecutablePath: mint run Carthage/Carthage carthage
configs:
  DebugDevelopment: debug
  DebugProduction: debug
  ReleaseDevelopment: release
  ReleaseProduction: release
settings:
  base:
    MARKETING_VERSION: 1.0.0
    BUILD_VERSION: 1
targets:
  Component:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: Component
    dependencies:
      - carthage: Nuke
  QiitaVIPER:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: QiitaVIPER
    dependencies:
      - target: Component
      - target: Model
      - sdk: Webkit.framework
    preBuildScripts:
      - name: "[SwiftLint] Run Script"
        script: "make swiftlint"
      - name: "[SwiftFormat] Run Script"
        script: "make swiftformat-diff"
  Model:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources: Model
    dependencies:
      - carthage: Alamofire

